### ISSUE TITLE
Basic requirements

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/nc_ext_dav_push#31]
- [x] Change element hierarchy and names to current draft
    - There's now a normative formal reference (although it may still change): [XML Schema](https://bitfireat.github.io/webdav-push/draft-bitfire-webdav-push-00.html#section-7).

- [x] Handle subscription registration
  - [x] handle requested <expires> and cap to a reasonable default (1 week) – #23
  - [x] returns `Expires` header – reasonable default (1 week) – #23
  - [x] returns `Location` header

- [x] Handle subscription update
  - [x] returns `Expires` and `Location`, like on registration

- [x] Handle subscription removal – #17

- [x] Notification:
  - [x] on add calendar object
  - [x] on change calendar object
  - [x] on delete calendar object – #30
  - [x] contains collection `sync-token`
  - [x] contains collection `topic`

- [x] Clean up expired subscriptions – #23
- [x] Clean up invalid subscriptions – #24
  - at least the one that return 4xx, others may be kept until they expire

**Comment by bonswouar** [comment]
Does this mean that
>  push subscriptions currently don't expire and won't be removed when they have become invalid

can be removed from the README? :)
